apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "fiddlepad.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fiddlepad.name" . }}
    helm.sh/chart: {{ include "fiddlepad.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fiddlepad.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fiddlepad.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: celestialc.ad.selinc.com:5000/selangfiddle:0.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: fiddle-storage-standardlib
              mountPath: /var/libs/jetty/webapps/lib/standardlib
            - name: fiddle-storage-userlib
              mountPath:  /var/libs/jetty/webapps/lib/userlib
      volumes:
        - name: fiddle-storage-standardlib
          persistentVolumeClaim:
            claimName: fiddlepad-pv-claim
        - name: fiddle-storage-userlib
          persistentVolumeClaim:
            claimName: fiddlepad-pv-claim
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
          
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: fiddlepad-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
