{{- if .Values.server.ingress.enabled -}}
{{- $fullName := include "fiddlepad.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
  name: {{ $fullName }}
{{- if .Values.server.ingress.annotations }}
  annotations:
{{ toYaml .Values.server.ingress.annotations | indent 4 }}
{{- end  }}

    
spec:
  rules:
  {{- range .Values.server.ingress.hosts}}
     {{- $url := splitList "/" . }}
  - host: {{ first $url }}
    http: 
      paths: 
        - path: /
          backend:
            serviceName: fiddlepad-cluster-ip #this will need to be changed to my actual service name 
            servicePort: 8080
  {{- end -}}

       
{{- end -}}
  