apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagebus
spec:
  selector:
    matchLabels:
      app: messagebus
  template:
    metadata:
      labels:
        app: messagebus
    spec:
      containers:
      - name: messagebus
        image: sel-docker.artifactory.metro.ad.selinc.com/nats
        ports:
        - containerPort: 4222
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daveysocket
spec:
  selector:
    matchLabels:
      app: daveysocket
  template:
    metadata:
      labels:
        app: daveysocket
    spec:
      containers:
      - name: daveysocket
        image: celestialc.ad.selinc.com:5000/daveysocket:0.1
        ports:
        - containerPort: 8080
        env:
          - name: MessageBusAddress
            value: messagebus-cluster-ip
          